### ISSUE TITLE
Archetype is not working

### ISSUE THREAD

**Issue by sandwwraith** [edvin/tornadofx-quickstart-archetype#2]
When I try to call `jfx:run` right after installing an archetype, I have got an error: `java.lang.ClassNotFoundException: me.sandwwraith.MyAppKt`. I think it's because file `MyApp.kt` is compiled to `MyApp.class`, but in javafx maven configuration main class set to `MyAppKt`.

If I fix the pom, I've got another error: 
```
java.lang.Exception: The specified mainClass doesn't contain a main method with appropriate signature.
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodException: me.sandwwraith.MyApp.main([Ljava.lang.String;)
	at java.lang.Class.getMethod(Class.java:1786)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:281)
	... 1 more

```

And I don't know how to fix it.

**Comment by edvin** [comment]
I'm sorry about this. It seems that the `jfx:run` target is unable to recognize the `App` class, you you need to add this to the bottom of `MyApp.kt`:

``` kotlin
fun main(args: Array<String>) {
    Application.launch(MyApp::class.java, *args)
}
```

Revert the `mainClass` argument to `MyAppKt`.

I will update the sample and release a new version of the archetype after the 1.5.8 release, probably this coming weekend.

Can you confirm if this is working for you?

**Comment by sandwwraith** [comment]
Yep, this is working, thanks :)

Btw, I noticed that file `MainView.kt` contains line `package me.sandwwraith.view`, but actually it is located in `src/me/sandwwraith/viewS`. Is this an error or not?

**Comment by edvin** [comment]
That's another bug :) Committed a fix for it now, thanks again :)
