### ISSUE TITLE
Archetype's MyApp contains import errors that break the build

### ISSUE THREAD

**Issue by carltonwhitehead** [edvin/tornadofx-quickstart-archetype#3]
Steps to repeat issue:

1. Follow the instructions to generate an app using the archetype per the tornadofx readme
```no-highlight
mvn archetype:generate -DarchetypeGroupId=no.tornado \
  -DarchetypeArtifactId=tornadofx-quickstart-archetype \
  -DarchetypeVersion=1.7.10
```
2. cd into the generated app folder and attempt to build/run with `mvn jfx:run`

Expected result
App builds and launches

Actual result
App fails to build with the following errors
```no-highlight
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.1.3-2:compile (compile) on project hello: Compilation failure: Compilation failure:
[ERROR] {trimmed} /MyApp.kt:[3,30] Unresolved reference: view
[ERROR] {trimmed} /MyApp.kt:[6,18] Unresolved reference: MainView
[ERROR] {trimmed} /MyApp.kt:[12,5] Unresolved reference: Application
```

**Comment by carltonwhitehead** [comment]
It seems like there are just some wrong imports. I'll send you a PR momentarily

**Comment by edvin** [comment]
Great, thank you! If you want, you can update the Kotlin version reference to 1.1.4-3 as well. I'll push a new version of it once you submit the PR.

**Comment by edvin** [comment]
Never mind, I merged your PR, will make the Kotlin version change and push a new version now :)

**Comment by edvin** [comment]
Version 1.7.10.2 is available in Maven Central with this fix now :)

**Comment by carltonwhitehead** [comment]
Thanks @edvin -- works properly now!

**Comment by edvin** [comment]
Great! Thanks for reporting and fixing :)
